### ISSUE TITLE
Update 4.5 -> 4.7 seems problematic

### ISSUE THREAD

**Issue by bloatware** [textpattern/textpattern#1242]
The function `load_lang()` is run before the update script. But in 4.7 it uses `owner` column absent in 4.5 and issues a warning just before update. Not sure for the final effect.

**Comment by Bloke** [comment]
Will check this out, thanks. Probably we need to dial back the use of owner, or add some defensive code to check if it exists first.

**Comment by petecooper** [comment]
If I can clear a few hours tonight for testing, what can I do here to help this along?

**Comment by bloatware** [comment]
@petecooper if you can install a fresh 4.5.7 (I have failed) and then try to upgrade to 4.7, that would be ace. I had some db errors on upgrade from an old 4.5 to 4.7, but it might be me. Thanks!

**Comment by petecooper** [comment]
@bloatware - sure thing. Do you want any kind of extra debug information, if indeed that's possible?

**Comment by bloatware** [comment]
@petecooper yes, please, do it in debug mode. AFAIR, I got some "unknown 'owner' field" message.

**Comment by petecooper** [comment]
@bloatware - I've built a VirtualBox VM with Ubuntu 14.04LTS with Textpattern 4.5.7 ready to go, with snapshots for various steps along the way. Would you like a copy for your testing arsenal?

I will try the 4.5.7 to 4.7.0 next and report back.

**Comment by petecooper** [comment]
Confirmed 4.5.7 to 4.7.0-dev is fatal.

**STR**
* install vanilla 4.5.7 (please ask if you want a prepared VM)
* enable debugging mode
* follow standard upgrade instructions
* note error text on admin-side and front-side

**Admin error text**
```
internal_error.
User_Error "Unknown column 'owner' in 'where clause'"
in /var/www/html/textpattern/lib/txplib_db.php at line 410.
adminErrorHandler()
textpattern/lib/txplib_db.php:410 trigger_error()
textpattern/lib/txplib_db.php:1136 safe_query()
textpattern/lib/txplib_db.php:984 startRows()
textpattern/vendors/Textpattern/L10n/Lang.php:551 safe_rows_start()
textpattern/vendors/Textpattern/L10n/Lang.php:578 Textpattern\L10n\Lang->extract()
textpattern/lib/txplib_misc.php:507 Textpattern\L10n\Lang->load()
textpattern/index.php:198 load_lang()
User_Error "Duplicate entry '1-permlink_format-' for key 'prefs_idx'"
in /var/www/html/textpattern/lib/txplib_db.php at line 410.
textpattern/lib/txplib_misc.php:1715 adminErrorHandler()
updateErrorHandler()
textpattern/lib/txplib_db.php:410 trigger_error()
textpattern/lib/txplib_db.php:460 safe_query()
textpattern/update/_to_4.6.0.php:42 safe_update()
textpattern/update/_update.php:91 include()
textpattern/index.php:218 include()
User_Error "Unknown column 'owner' in 'where clause'"
in /var/www/html/textpattern/lib/txplib_db.php at line 410.
textpattern/lib/txplib_misc.php:1715 adminErrorHandler()
updateErrorHandler()
textpattern/lib/txplib_db.php:410 trigger_error()
textpattern/lib/txplib_db.php:1106 safe_query()
textpattern/lib/txplib_db.php:951 getRows()
textpattern/vendors/Textpattern/L10n/Lang.php:254 safe_rows()
textpattern/update/_update.php:115 Textpattern\L10n\Lang->available()
textpattern/index.php:218 include()

Fatal error: Uncaught exception 'Exception' with message 'update failed' in /var/www/html/textpattern/lib/txplib_misc.php:1719 Stack trace: #0 [internal function]: updateErrorHandler(256, 'Unknown column ...', '/var/www/html/t...', 410, Array) #1 /var/www/html/textpattern/lib/txplib_db.php(410): trigger_error('Unknown column ...', 256) #2 /var/www/html/textpattern/lib/txplib_db.php(1106): safe_query('SELECT lang, UN...', false) #3 /var/www/html/textpattern/lib/txplib_db.php(951): getRows('SELECT lang, UN...', false) #4 /var/www/html/textpattern/vendors/Textpattern/L10n/Lang.php(254): safe_rows('lang, UNIX_TIME...', 'txp_lang', 'owner = '' GROU...') #5 /var/www/html/textpattern/update/_update.php(115): Textpattern\L10n\Lang->available(3, 7) #6 /var/www/html/textpattern/index.php(218): include('/var/www/html/t...') #7 {main} thrown in /var/www/html/textpattern/lib/txplib_misc.php on line 1719
```

**Front error text**
```
general_error Textpattern Error: Unknown column 'owner' in 'where clause' on line 410
textpattern/lib/txplib_db.php:410 trigger_error()
textpattern/lib/txplib_db.php:1136 safe_query()
textpattern/lib/txplib_db.php:984 startRows()
textpattern/vendors/Textpattern/L10n/Lang.php:551 safe_rows_start()
textpattern/vendors/Textpattern/L10n/Lang.php:578 Textpattern\L10n\Lang->extract()
textpattern/lib/txplib_misc.php:507 Textpattern\L10n\Lang->load()
textpattern/publish.php:188 load_lang()
index.php:107 include()
general_error Textpattern Error: Unknown column 'skin' in 'field list' on line 410
textpattern/lib/txplib_db.php:410 trigger_error()
textpattern/lib/txplib_db.php:1077 safe_query()
textpattern/lib/txplib_db.php:916 getRow()
textpattern/publish.php:526 safe_row()
textpattern/publish.php:204 preText()
index.php:107 include()
Tag error:  ->  Textpattern Error: Unknown column 'skin' in 'where clause' while parsing form none on page none
textpattern/lib/txplib_db.php:410 trigger_error()
textpattern/lib/txplib_db.php:829 safe_query()
textpattern/lib/txplib_misc.php:4396 safe_field()
textpattern/lib/txplib_misc.php:4426 fetch_page()
textpattern/publish.php:581 parse_page()
index.php:116 textpattern()
Tag error:  ->  Textpattern Error: Unknown column 'skin' in 'field list' while parsing form none on page none
textpattern/lib/txplib_db.php:410 trigger_error()
textpattern/lib/txplib_db.php:829 safe_query()
textpattern/lib/txplib_misc.php:5282 safe_field()
textpattern/publish.php:584 txp_die()
index.php:116 textpattern()
Tag error:  ->  Textpattern Error: Unknown column 'skin' in 'where clause' while parsing form none on page none
textpattern/lib/txplib_db.php:410 trigger_error()
textpattern/lib/txplib_db.php:829 safe_query()
textpattern/lib/txplib_misc.php:5289 safe_field()
textpattern/publish.php:584 txp_die()
index.php:116 textpattern()
Unknown section
```

Slightly rough screencast attached, plus before and after databases (there are differences).

[1242.mp4.zip](https://github.com/textpattern/textpattern/files/1956886/1242.mp4.zip)

[1242-textpattern457-before.sql.zip](https://github.com/textpattern/textpattern/files/1956864/1242-textpattern457-before.sql.zip)

[1242-textpattern457-after.sql.zip](https://github.com/textpattern/textpattern/files/1956865/1242-textpattern457-after.sql.zip)

You want me to try with 4.4.x, too?

**Comment by petecooper** [comment]
PS: `Verification required` badge can be removed.

**Comment by petecooper** [comment]
Just tried 4.4.1 -> 4.7.0-dev with different results. Summarised:

* I can log in, unlike 4.5.7
* one-off error that I didn't catch but can reproduce if of use
* persistent error in admin-side:

```
User_Error "Duplicate entry 'permlink_format-' for key 'prefs_idx'"
in /var/www/html/textpattern/lib/txplib_db.php at line 410.
textpattern/lib/txplib_misc.php:1715 adminErrorHandler()
updateErrorHandler()
textpattern/lib/txplib_db.php:410 trigger_error()
textpattern/lib/txplib_db.php:545 safe_query()
textpattern/update/_to_4.7.0.php:38 safe_alter()
textpattern/update/_update.php:91 include()
textpattern/index.php:218 include()
```

* front side error:

```
General error Textpattern Error: Unknown column 'skin' in 'field list' on line 410
textpattern/lib/txplib_db.php:410 trigger_error()
textpattern/lib/txplib_db.php:1077 safe_query()
textpattern/lib/txplib_db.php:916 getRow()
textpattern/publish.php:526 safe_row()
textpattern/publish.php:204 preText()
index.php:107 include()
Tag error:  ->  Textpattern Error: Unknown column 'skin' in 'where clause' while parsing form None on page None
textpattern/lib/txplib_db.php:410 trigger_error()
textpattern/lib/txplib_db.php:829 safe_query()
textpattern/lib/txplib_misc.php:4396 safe_field()
textpattern/lib/txplib_misc.php:4426 fetch_page()
textpattern/publish.php:581 parse_page()
index.php:116 textpattern()
Tag error:  ->  Textpattern Error: Unknown column 'skin' in 'field list' while parsing form None on page None
textpattern/lib/txplib_db.php:410 trigger_error()
textpattern/lib/txplib_db.php:829 safe_query()
textpattern/lib/txplib_misc.php:5282 safe_field()
textpattern/publish.php:584 txp_die()
index.php:116 textpattern()
Tag error:  ->  Textpattern Error: Unknown column 'skin' in 'where clause' while parsing form None on page None
textpattern/lib/txplib_db.php:410 trigger_error()
textpattern/lib/txplib_db.php:829 safe_query()
textpattern/lib/txplib_misc.php:5289 safe_field()
textpattern/publish.php:584 txp_die()
index.php:116 textpattern()
Unknown section
```

**Comment by bloatware** [comment]
Thanks, @petecooper. It's even worse then, I have no idea for 4.4->4.7 error. Not using VM atm, but will ask you for a copy if needed.

**Comment by bloatware** [comment]
@petecooper could you retest if 4.5->4.7 is fixed, please?

**Comment by petecooper** [comment]
Yes -- can you assign this to me and I'll test this evening.

**Comment by jools-r** [comment]
[This line](https://github.com/textpattern/textpattern/commit/5da8523867861937fa12632b5f35340860a99c62#diff-d79294d41f4c07f4da46013c5b82c8efR546) is what is causing the MySQL syntax error and preventing the language strings from loading.

I just tried upgrading a 4.3 version of an old site if mine and experienced similar/identical messages to Pete's. With a couple of public side reloads / admin logout / logins, plus deleting the duplicate pref, the warnings all gradually disappear. Just the MySQL warning returned until I reverted the above line.

**Comment by bloatware** [comment]
[Shame](https://github.com/textpattern/textpattern/commit/4b5f18c1542c5b44db656d731049fb38d09d9707) on me

**Comment by philwareham** [comment]
Is this fixed now? Thanks.

**Comment by petecooper** [comment]
I'll retest here this morning and report back.

**Comment by petecooper** [comment]
I'm still getting an admin-side error on login (note: no `internal error.` this time):

```
User_Error "Duplicate entry '1-permlink_format-' for key 'prefs_idx'"
in /var/www/html/textpattern-4.5.7/textpattern/lib/txplib_db.php at line 410.
textpattern/lib/txplib_misc.php:1715 adminErrorHandler()
updateErrorHandler()
textpattern/lib/txplib_db.php:410 trigger_error()
textpattern/lib/txplib_db.php:460 safe_query()
textpattern/update/_to_4.6.0.php:42 safe_update()
textpattern/update/_update.php:91 include()
textpattern/index.php:218 include()
User_Error "Unknown column 'owner' in 'where clause'"
in /var/www/html/textpattern-4.5.7/textpattern/lib/txplib_db.php at line 410.
textpattern/lib/txplib_misc.php:1715 adminErrorHandler()
updateErrorHandler()
textpattern/lib/txplib_db.php:410 trigger_error()
textpattern/lib/txplib_db.php:1106 safe_query()
textpattern/lib/txplib_db.php:951 getRows()
textpattern/vendors/Textpattern/L10n/Lang.php:254 safe_rows()
textpattern/update/_update.php:115 Textpattern\L10n\Lang->available()
textpattern/index.php:218 include()

Fatal error: Uncaught exception 'Exception' with message 'update failed' in /var/www/html/textpattern-4.5.7/textpattern/lib/txplib_misc.php:1719 Stack trace: #0 [internal function]: updateErrorHandler(256, 'Unknown column ...', '/var/www/html/t...', 410, Array) #1 /var/www/html/textpattern-4.5.7/textpattern/lib/txplib_db.php(410): trigger_error('Unknown column ...', 256) #2 /var/www/html/textpattern-4.5.7/textpattern/lib/txplib_db.php(1106): safe_query('SELECT lang, UN...', false) #3 /var/www/html/textpattern-4.5.7/textpattern/lib/txplib_db.php(951): getRows('SELECT lang, UN...', false) #4 /var/www/html/textpattern-4.5.7/textpattern/vendors/Textpattern/L10n/Lang.php(254): safe_rows('lang, UNIX_TIME...', 'txp_lang', 'owner = '' GROU...') #5 /var/www/html/textpattern-4.5.7/textpattern/update/_update.php(115): Textpattern\L10n\Lang->available(3, 7) #6 /var/www/html/textpattern-4.5.7/textpattern/index.php(218): include('/var/www/html/t...') #7 {main} thrown in /var/www/html/textpattern-4.5.7/textpattern/lib/txplib_misc.php on line 1719
```

**Comment by Bloke** [comment]
I'm testing too -from even further back - but hitting all sorts of snags. Not least of which is that after logging into the admin side and navigating to any other tab I get kicked out back to the login screen. Doesn't seem to be storing the cookie on localhost for some reason. Or MAMP is misconfigured somehow. I did have to dial it back to use an older version of PHP and put up with the constant warnings about `mysql_*()` being deprecated. Weird though.

Anyway, when I eventually do find a version that lets me actually log in and stay logged in, I'll also run through some tests later. We need to trace that duplicate key issue. My best guess is it's to do with the fact we renamed that pref last version, and also removed the old index column. Perhaps the old pref is still "there" during upgrade, which clashes with the new name when we kill the `prefs_idx`column? Maybe we simply need to make sure old prefs are deleted first during the upgrade?

**Comment by jools-r** [comment]
Having already upgraded I don't see the other errors. The [error mentioned above](https://github.com/textpattern/textpattern/issues/1242#issuecomment-385553353) is resolved but I still get all plugin language strings as the gTxt names.

**Comment by petecooper** [comment]
I'll have time this evening to help with this, and I can make some VirtualBox prefab images if you want a disposable/snapshot-able LAMP environment to use.

**Comment by Bloke** [comment]
Dammit, we use `owner` all over the place in `L10n/Lang.php`. We can probably get away with the ones in `upsertPack()` (maybe) since that is only run _after_ the database changes have occurred. But the one in the `available()` method is causing issues, as Pete found out.

That means more version checks or a better workaround. Peppering the methods in this class with 'if version' checks is kind of annoying. I'd rather:

a) Centralize the version check so all Lang methods can use it and act accordingly, thus the "magic version number" string only appears once in the class.

b) Fix the issue properly somehow. Not sure how to do this though, as we need lang strings from the get-go.

**Comment by jools-r** [comment]
Addendum to [the note above](https://github.com/textpattern/textpattern/issues/1242#issuecomment-385633770): the reason for that was the pref `version` was still at 4.3.0 and hadn't been updated. Manually changing it to 4.7.0 restores the correct plugin languages behaviour. So it may not be that line but part of the preceding semi-borked update.

**Comment by Bloke** [comment]
I'm confused by this:

```
User_Error "Unknown column 'owner' in 'where clause'"
in /var/www/html/textpattern-4.5.7/textpattern/lib/txplib_db.php at line 410.
textpattern/lib/txplib_misc.php:1715 adminErrorHandler()
updateErrorHandler()
textpattern/lib/txplib_db.php:410 trigger_error()
textpattern/lib/txplib_db.php:1106 safe_query()
textpattern/lib/txplib_db.php:951 getRows()
textpattern/vendors/Textpattern/L10n/Lang.php:254 safe_rows()
textpattern/update/_update.php:115 Textpattern\L10n\Lang->available()
textpattern/index.php:218 include()
```

By the time this line is reached in `_update.php` all database modifications have been performed (i.e. all `_to_x.y.z.php` files have been processed) and this database column should therefore exist.

Head scratch...

**Comment by petecooper** [comment]
@Bloke - I can re-run it this evening when I have a bit of time - are the before & after db dumps any use?

**Comment by Bloke** [comment]
Going from an even earlier version (4.0.0 in this case: okay okay, extreme!) yields even more problems, but this may also affect anyone on 4.2.0:

```
Warning "include(/path/to/textpattern/update/_to_1.0.0.php): failed to open stream: No such file or directory"
in /path/to/textpattern/update/_update.php at line 91.

textpattern/lib/txplib_misc.php:1715 adminErrorHandler()
textpattern/update/_update.php:91 updateErrorHandler()
textpattern/update/_update.php:91 include()
textpattern/index.php:218 include()

User_Error "Unknown column 'user_name' in 'where clause'"
in /path/to/textpattern/lib/txplib_db.php at line 410.

textpattern/lib/txplib_misc.php:1715 adminErrorHandler()
updateErrorHandler()
textpattern/lib/txplib_db.php:410 trigger_error()
textpattern/lib/txplib_db.php:829 safe_query()
textpattern/lib/txplib_misc.php:4796 safe_field()
textpattern/vendors/Textpattern/L10n/Lang.php:244 get_pref()
textpattern/update/_update.php:115 Textpattern\L10n\Lang->available()
textpattern/index.php:218 include()
```

We can probably get round the missing 1.0.0 file (and indeed the 4.0.2 file) by just removing those entries from the `$dbupdates` array in `_update.php`. They probably shouldn't be there anyway as those files no longer exist. Not sure if that has any impact anywhere else, but I suspect not.

The second error `Unknown column 'user_name' in 'where clause'` is way more problematic. That stems from a call to `get_pref()` (and possibly by inference `get_prefs()`) which assumes the column  exists. It doesn't in all versions prior to 4.2.0.

So we have a problem here which can be solved in two main ways:

1) Patch `get_pref()` - and possibly any other functions that rely on this column - to only use `user_name` if the db version is > 4.2.0. The irony being we need to check the prefs to find out the version number (but at least that doesn't rely on the user name as it's a global pref)! That may well also fix the "known issue" when upgrading to 4.2.0 highlighted in the README.

2) Update our docs / READMEs and state if you want to make huge leaps, it's better to do it incrementally. And offer some suggestions, like jumping from 4.0.x to 4.2.0 first. Then to 4.5.7. Then finally to 4.7.0 (once we fix all the problems here).

Thoughts?

**Comment by bloatware** [comment]
> By the time this line is reached in _update.php all database modifications have been performed (i.e. all _to_x.y.z.php files have been processed) and this database column should therefore exist.

Unlikely, but could there be a delay before the column is actually created? Does sleeping few seconds help?

**Comment by petecooper** [comment]
Can we buildout a grid of what works and what doesn't version-wise? It's not beyond the realms of reasonable to have veeeerrrrryyyy old versions move to 4.6.2 first, _then_ make a jump to the most recent version.

I have a vague memory of @vanmelick opening (or adding to) an issue where really old versions should be out of official support, but it's hazy.

**Comment by Bloke** [comment]
Sure, I've got no issues with supporting only recentish builds from a direct upgrade stance. Especially since it's possilbe to upgrade to the latest from the earliest, with a couple of hoops to jump through. Basic rule of thumb:

* Anything prior to 4.2.0, jump to 4.2.0 first and let it get the `unknown user_name` issues out of its system first by doing a few login cycles / admin tab dances.
* Anything between 4.2.0 and 4.5.x should jump to 4.5.7 first before attempting the leap to 4.6.x.
* Anyone going from 4.5.7 should set their production status to live, log out of the admin side first and _then_ do the upgrade. This is mainly of importance if going to 4.6.2 or using non-standard MySQL clones; 4.7.0 should be fine via direct leap without the production status dance... once we close down any issues in this thread.
* Anyone running non-MySQL clones should avoid 4.6.2 and go straight to 4.7.0. Do not pass go. Do not collect £200.

The final caveat to all the above is that you can't run anything earlier than 4.6 on PHP 7+ or it will just explode in a shower of 1s and 0s.

**Comment by petecooper** [comment]
I found that @vanmelick thread: https://github.com/textpattern/textpattern/issues/574

**Comment by Bloke** [comment]
Yep, and if we get this thread licked, we can get people to jump straight from 4.5.7 to 4.7.0. Save a row, save the world.

**Comment by petecooper** [comment]
@Bloke - what would you like tested? I can squeeze a couple of hours this evening.

**Comment by Bloke** [comment]
Thank you. Ideally it should work with any site status. Debugging will give you the greatest chance of seeing any snafus. We'll try and sneak some patches in early evening to catch some of the edge cases you've found.

("we", may be "I" if I get time).

**Comment by Bloke** [comment]
See 77b64c09 for a partial fix to the Duplicate entry bug. Probably just need to tweak `DB/Core.php` now to copy its value across. Will do that next.

**Comment by Bloke** [comment]
Nice, thanks. There is still one issue to resolve (and I haven't had a chance to do it so if anyone wants to jump in, please do so). It's related to 77b64c09. During setup we have a process for:

1) Deleting old prefs
2) Installing new ones

But we don't have a mechanism for _moving_ prefs to a new name and retaining their old values.

We need to add a `renamed.prefs` file so we can specify old key => new key name mappings. Then it's just a simple case of introducing this facility at the start of `DB/Core.php->checkPrefsIntegrity()` by looping over the renamed prefs array and calling `rename_pref()`.

We'll need to retain the same situation as in the `deleted.prefs` file with regards defining "global" and "private" subkeys in the JSON file so we know whether to pass the 3rd argument to `rename_pref()` or not. Fairly easy. Probably a 15-minute job but I'm swamped today.

**Comment by philwareham** [comment]
If we can get this last issue fixed - I think we are good to go on a RC1. If we can aim to get final release out on 15th May then that would be perfect - otherwise I would not be around for ~2 weeks and we would be past the GDPR deadline on my return. RC1 only needs 3-4 days on testing IMO.

**Comment by Bloke** [comment]
Please test the fix in 4781f5b for both installs, and upgrades where the `permlink format` is set to either value. The pref and its value should be migrated.

**Comment by Bloke** [comment]
There should also be less badness surrounding language errors thrown when upgrading from earlier versions too, courtesy of 999edbf2. Again, testing welcome. If we can extend the experience for people upgrading from 4.2.0 directly to 4.7.0, that'd be great. But if that's not possible we'll publish the essence of Pete's table above.

**Comment by petecooper** [comment]
For completeness, a 4.5.7 -> 4.7.0 jump with current `dev` branch:

STR:
* install vanilla 4.5.7
* set permlinks to interCapped, set Debugging mode, log out
* follow upgrade instructions

Pre-jump stuff:

![safariscreensnapz014](https://user-images.githubusercontent.com/226578/39832791-19627dd6-53c0-11e8-9764-33a537f35701.png)
![safariscreensnapz013](https://user-images.githubusercontent.com/226578/39832792-1978f6ce-53c0-11e8-87d1-e4ebca6819ec.png)
![safariscreensnapz009](https://user-images.githubusercontent.com/226578/39832793-1991f3d6-53c0-11e8-901d-f64361877686.png)

Clean jump, zero errors:

![safariscreensnapz019](https://user-images.githubusercontent.com/226578/39832890-6c5b786c-53c0-11e8-8f3e-147611023ca5.png)
![safariscreensnapz017](https://user-images.githubusercontent.com/226578/39832891-6c70811c-53c0-11e8-99b9-abe9c240c284.png)
![safariscreensnapz016](https://user-images.githubusercontent.com/226578/39832892-6c861c66-53c0-11e8-9cf6-caf43295cab8.png)
![safariscreensnapz015](https://user-images.githubusercontent.com/226578/39832893-6c9c74e8-53c0-11e8-8781-095eb067abc6.png)

**Comment by petecooper** [comment]
…and in the spirit of Go Hard Or Go Home, I'll be back with pre-4.2.0 reports if I manage to get anything installed _at all_.

**Comment by Bloke** [comment]
Awesome! Thanks for the detailed testing. Really great news that it's possible to jump from 4.2.0 direct now.

I had real issues - as you did/will - getting anything earlier to run at all on my MAMP setup. I had to first rename the 7.x versions of PHP in `/Applications/MAMP/bin/php/` so they didn't show up in MAMP's control panel, choose the lowest version supported (5.4.45) and even then it was an absolute mess. The main problem was that it couldn't store the login cookie because of all the debugging crap thrown to the screen so I had to re-log in every time I switched admin panel. Fuuuun.

But if you can fake a cookie (or at least log in with a later version, set the cookie, _don't_ log out then import an old DB dump and downgrade Txp, you might be able to at least get something limping along.

But don't sweat it if you can't. An 8.5 year jump is still mighty impressive!

**Comment by petecooper** [comment]
Alright. Buckle up. 4.0.0 -> 4.7.0-dev just happened.

STR:
* install ye olde LAMP server from the year of our lord 2006 (I went with Ubuntu 6.06LTS)
* install Textpattern 4.0.0
* set debugging mode, set permlinks to interCaps
* update ye olde LAMP server to a newer vintage (I bumped to 8.04LTS then 10.04LTS in two hops, second hop met Textpattern system requirements)
* log out
* upgrade to 4.7.0-dev

Textpattern 4.0.0 running:

![safariscreensnapz022](https://user-images.githubusercontent.com/226578/39835920-a945006e-53c9-11e8-8ad1-0b387bcaa0f9.png)

Debugging and interCaps:

![safariscreensnapz020](https://user-images.githubusercontent.com/226578/39835930-af8cf17a-53c9-11e8-8a20-bb5f6dcd2028.png)

![safariscreensnapz021](https://user-images.githubusercontent.com/226578/39835931-afa6422e-53c9-11e8-8686-8e895654172f.png)

…after the jump to Ubuntu 8.04LTS (newer AMP components):

![safariscreensnapz023](https://user-images.githubusercontent.com/226578/39835971-d10b0ec2-53c9-11e8-8e13-9b117d0c299f.png)

…and then to Ubuntu 10.04LTS (newer AMP components again):

![safariscreensnapz024](https://user-images.githubusercontent.com/226578/39837070-44c2e4b8-53cd-11e8-9546-4a9c05a2f8f8.png)

Note that in-place upgrades to Ubuntu started getting tricky because of legacy cruft, and Textpattern requirements weren't met, so I used a fresh ISO to build a fresh OS with native AMP stack. Back on the air after that, Textpattern 4.0.0 on barebones 10.04 LTS (marginally different AMP versions):

![safariscreensnapz029](https://user-images.githubusercontent.com/226578/39838569-a6729a4c-53d1-11e8-99be-3f4543568a8e.png)

…and an in-place update brings a few more updates – nearly at minimum requirements:

![safariscreensnapz026](https://user-images.githubusercontent.com/226578/39838690-f6837b14-53d1-11e8-86fe-26d6354ef772.png)

Let's shoot for an upgrade and live dangerously. Confirming interCaps and debugging as before:

![safariscreensnapz027](https://user-images.githubusercontent.com/226578/39838819-593f8090-53d2-11e8-9540-65f4a619f4ae.png)

![safariscreensnapz028](https://user-images.githubusercontent.com/226578/39838820-595723ee-53d2-11e8-9c95-dcd73f3be395.png)

I have a feeling this might not work. Drop dev files in place, replace `config.php`, try logging in:

![safariscreensnapz031](https://user-images.githubusercontent.com/226578/39838994-c1083f1e-53d2-11e8-84e0-bec561918f16.png)

Score! Very smart. I tried and failed to compile from source, so ended up jumping to 12.04 LTS with native AMP instead:

![safariscreensnapz032](https://user-images.githubusercontent.com/226578/39841129-b4fd4de8-53d9-11e8-8df7-49292ca3b7d6.png)

Now we're in business. FYI Ubuntu 12.04 LTS is the sweet spot – 4.0.0 runs with a warning (`Deprecated: Function split() is deprecated in /var/www/textpattern/include/txp_auth.php on line 105`) in all modes, but it's smooth sailing beyond that. The installed AMP versions from the ISO meet system requirements, but don't exceed by much.

Confirming interCaps and Debugging mode:

![safariscreensnapz033](https://user-images.githubusercontent.com/226578/39841269-1e4f0098-53da-11e8-9c6f-ce8be1e3206b.png)
![safariscreensnapz034](https://user-images.githubusercontent.com/226578/39841270-1e65639c-53da-11e8-9866-52490eca4efa.png)

Alright. Drum roll. Log out, drop files into place, replace `config.php`, and shoot for an upgrade:

```
Warning "include(/var/www/textpattern/update/_to_1.0.0.php): failed to open stream: No such file or directory"
in /var/www/textpattern/update/_update.php at line 91.
textpattern/lib/txplib_misc.php:1715 adminErrorHandler()
textpattern/update/_update.php:91 updateErrorHandler()
textpattern/update/_update.php:91 include()
textpattern/index.php:214 include()
User_Error "Unknown column 'user_name' in 'where clause'"
in /var/www/textpattern/lib/txplib_db.php at line 410.
textpattern/lib/txplib_misc.php:1715 adminErrorHandler()
updateErrorHandler()
textpattern/lib/txplib_db.php:410 trigger_error()
textpattern/lib/txplib_db.php:829 safe_query()
textpattern/lib/txplib_misc.php:4796 safe_field()
textpattern/vendors/Textpattern/L10n/Lang.php:244 get_pref()
textpattern/update/_update.php:115 Textpattern\L10n\Lang->available()
textpattern/index.php:214 include()
Fatal error: Uncaught exception 'Exception' with message 'update failed' in /var/www/textpattern/lib/txplib_misc.php:1719 Stack trace: #0 [internal function]: updateErrorHandler(256, 'Unknown column ...', '/var/www/textpa...', 410, Array) #1 /var/www/textpattern/lib/txplib_db.php(410): trigger_error('Unknown column ...', 256) #2 /var/www/textpattern/lib/txplib_db.php(829): safe_query('SELECT val FROM...', false) #3 /var/www/textpattern/lib/txplib_misc.php(4796): safe_field('val', 'txp_prefs', 'name = 'languag...') #4 /var/www/textpattern/vendors/Textpattern/L10n/Lang.php(244): get_pref('language', 'en', true) #5 /var/www/textpattern/update/_update.php(115): Textpattern\L10n\Lang->available(3, 7) #6 /var/www/textpattern/index.php(214): include('/var/www/textpa...') #7 {main} thrown in /var/www/textpattern/lib/txplib_misc.php on line 1719
```

Dang. So close.

**Comment by petecooper** [comment]
Alright, that was a wild ride.

[This table](https://github.com/textpattern/textpattern/issues/1242#issuecomment-385668626) is accurate – pre-4.2.0 needs to update to 4.2.0 first, then it should be OK for a jump to 4.7.0 in one swoop.

Caveats: empty, vanilla install with Debugging mode enabled.

OP is done -- let's close this.

**Comment by Bloke** [comment]
Wow. Closer than I expected. The warning about 1.0.0 being missing we can probably bypass easily enough as I mentioned in [my previous comment](https://github.com/textpattern/textpattern/issues/1242#issuecomment-385648206) by simply removing the entries that don't have corresponding files from `_update.php`. In this case, we don't need 1.0.0 and 4.0.2:

```php
$dbupdates = array(
    '4.0.3', '4.0.4', '4.0.5', '4.0.6', '4.0.7', '4.0.8',
    '4.2.0',
    '4.3.0',
    '4.5.0', '4.5.7',
    '4.6.0',
    '4.7.0',
);
```
The `user_name` thing is definitely an issue we can't get round without a bit of patching because `get_pref()` expects that column to exist. It'll potentially slow down the `get_pref()` call though (would need some caching in there) and since it's used a fair bit it's probably not worth the hassle right now.

For final release let's document this somewhere in the README/History/forum/docs site and live with a two-step jump for those upgrading from Cro-Magnon versions.

**Comment by petecooper** [comment]
>For final release let's document this somewhere in the README/History/forum/docs site and live with a two-step jump for those upgrading from Cro-Magnon versions.

I'll make a start on that now – https://github.com/textpattern/textpattern/issues/1257

**Comment by philwareham** [comment]
Totally off topic (kind of) but I’d really recommend MAMP Pro. It’s a cinch to add/change PHP versions per domain with it - plus lots of other stuff. Really worth the money.

**Comment by jools-r** [comment]
Stunning testing work there, Pete! Like Phil I use MAMP Pro, but although you can download past PHP versions for inclusion, I'm not sure you can go back quite as far as you did in your tests. *Cro-Magnon versions* – love that!

**Comment by NicolasGraph** [comment]
Hi,
I get the following error messages while upgrading from 4.5.7 to 4.7.1, :

```
User_Error "Invalid default value for 'Posted'"
in /Users/nicolasmorand/Sites/Archives/cerclemagazine.com/textpattern/lib/txplib_db.php at line 410.

textpattern/lib/txplib_misc.php:1715 adminErrorHandler()
updateErrorHandler()
textpattern/lib/txplib_db.php:410 trigger_error()
textpattern/lib/txplib_db.php:545 safe_query()
textpattern/update/_to_4.6.0.php:28 safe_alter()
textpattern/update/_update.php:91 include()
textpattern/index.php:214 include()

User_Error "Unknown column 'owner' in 'field list'"
in /Users/nicolasmorand/Sites/Archives/cerclemagazine.com/textpattern/lib/txplib_db.php at line 410.

textpattern/lib/txplib_misc.php:1715 adminErrorHandler()
updateErrorHandler()
textpattern/lib/txplib_db.php:410 trigger_error()
textpattern/vendors/Textpattern/L10n/Lang.php:496 safe_query()
textpattern/vendors/Textpattern/L10n/Lang.php:414 Textpattern\L10n\Lang->upsertPack()
textpattern/update/_update.php:121 Textpattern\L10n\Lang->installFile()
textpattern/index.php:214 include()


Fatal error: Uncaught exception 'Exception' with message 'update failed' in /Users/nicolasmorand/Sites/Archives/cerclemagazine.com/textpattern/lib/txplib_misc.php:1719 Stack trace: #0 [internal function]: updateErrorHandler(256, 'Unknown column ...', '/Users/nicolasm...', 410, Array) #1 /Users/nicolasmorand/Sites/Archives/cerclemagazine.com/textpattern/lib/txplib_db.php(410): trigger_error('Unknown column ...', 256) #2 /Users/nicolasmorand/Sites/Archives/cerclemagazine.com/textpattern/vendors/Textpattern/L10n/Lang.php(496): safe_query('INSERT INTO mag...') #3 /Users/nicolasmorand/Sites/Archives/cerclemagazine.com/textpattern/vendors/Textpattern/L10n/Lang.php(414): Textpattern\L10n\Lang->upsertPack(Array) #4 /Users/nicolasmorand/Sites/Archives/cerclemagazine.com/textpattern/update/_update.php(121): Textpattern\L10n\Lang->installFile('en-gb') #5 /Users/nicolasmorand/Sites/Archives/cerclemagazine.com/textpattern/index.php(214): include('/Users/nicolasm...') #6 {main} thrown in /Users/nicolasmorand/Sites/Archives/cerclemagazine.com/textpattern/lib/txplib_misc.php on line 1719
```

Is there a fix I missed?

Note: I have a few plugins installed, including MLP but I disabled all of them before upgrading.

**Comment by Bloke** [comment]
Do you have any articles with 'invalid' Posted/Modified dates? From 4.6.x, an invalid date is one that reads `0000-00-00 00:00:00`. Do a quick check in your DB for that value and if you find any and your MySQL server is set to strict (or you're using an off-brand MySQL clone such as Percona) then there's a good chance you'll hit this annoying issue.

**Comment by NicolasGraph** [comment]
> Do you have any articles with 'invalid' Posted/Modified dates? From 4.6.x, an invalid date is one that reads 0000-00-00 00:00:00.

I didn't find this value for the Posted field in the textpattern table; however, it is used as the default one, for the Posted field and also for Expires and LastMod. In think I read somewhere on the forum that these, or one of these, default value(s) should be empty, shouldn't they/it? Or should I use NULL for any of these fields?

**Comment by Bloke** [comment]
Using `NULL` should work. That's kind of what the `_to_4.6.0` script is supposed to do but sometimes it fails if strict mode is on, or if another MySQL client with different capabilities is in use. It sets:

```
Posted      = NOW()
Expires     = NULL
LastMod     = Posted
```

**Comment by NicolasGraph** [comment]
> Using NULL should work.

Thanks @Bloke.
Just to be sure; I should use NULL for Posted, Expires and LastMod?

**Comment by Bloke** [comment]
Can if you like, but using the three values I mentioned in my last post is what `_to_4.6.0` does so if you want it to be in line with that, then set them accordingly.

**Comment by NicolasGraph** [comment]
Ok, thanks, I misunderstood you, sorry.

**Comment by NicolasGraph** [comment]
Unfortunatly, untill now I was not able to do what the script failed to do. I get the same kind of error (`"Invalid default value for 'Posted'"`) from MySQL 5.7.21 (Mamp pro). I tried to disable the strict mode, without success apparently.

**Comment by Bloke** [comment]
Hmmm, well that explains why the script couldn't do it: if you can't change it manually via SQL then the script has no chance!

I know it's a bind, but can you alter the table structure from a MySQL client like phpMyAdmin or SequelPro? That might let you do it from the GUI. I know I had similar issues with some tables and I can't for the life of me remember how I got round it now :(

**Comment by NicolasGraph** [comment]
> I know it's a bind, but can you alter the table structure from a MySQL client like phpMyAdmin or SequelPro? That might let you do it from the GUI.

It failed from phpMyAdmin.

> Can you change it to 1970-01-01 00:00:00 as an interim step?

I'm going to try.

**Comment by Bloke** [comment]
Out of curiosity, what does `SELECT @@SESSION.sql_mode;` reveal?

**Comment by NicolasGraph** [comment]
> Out of curiosity, what does SELECT @@SESSION.sql_mode; reveal?

```
ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_...
```

**Comment by Bloke** [comment]
Anything about ` NO_ZERO_DATE`? If so, perhaps you can remove it for the session using a `set` command to set it to the value all your current variables, excluding `NO_ZERO_DATE` and make the modifications then?

**Comment by NicolasGraph** [comment]
> Anything about NO_ZERO_DATE?

Yes, I edited my previous comment to put the full text response and there is `NO_ZERO_DATE`.
I'm not sure how to change it with the `set` command but I'm going to take a look.

**Comment by Bloke** [comment]
I've never tried it but:
```
SET SESSION sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
```

should do the trick.

**Comment by NicolasGraph** [comment]
I think, everything is OK now; I still have some error messages but they are related to missinf MLP files.
In the DB, _Expires_ is now `NULL`where it was `0000-00-00 00:00:00`.
I have also the following default values:

```
Posted: None
Expires: NULL
LastMod: None
```
I followed [this tip](http://blog-en.mamp.info/2010/02/how-to-set-mysql-default-storage-engine.html) to find whre to set `sql_mode` in Mamp pro.

**Comment by NicolasGraph** [comment]
I still have a weird issue in fact, which seems to be related to [this thread](https://forum.textpattern.io/viewtopic.php?id=46706) and should be already fixed.
On the public side, no article appear in lists, only on individual pages, and I get several error messages related to the _Expires_ value:

```
Tag error: <txp:article_custom section="a-propos" id="4, 5, 13" wraptag="ul" break="li"><a href='<txp:permlink />'><txp:title /></a></txp:article_custom> ->  Textpattern Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND (from_unixtime(2147483647) <= Expires OR Expires IS NULL) AND ID  IN (4,5,13' at line 1 while parsing form vsv_found_footer on page vsv_found_magazine

textpattern/lib/txplib_db.php:418 trigger_error()
textpattern/lib/txplib_db.php:1162 safe_query()
textpattern/lib/txplib_db.php:1004 startRows()
textpattern/publish.php:850 safe_rows_start()
textpattern/publish.php:971 doArticles()
textpattern/publish.php:960 parseArticles()
article_custom()
textpattern/vendors/Textpattern/Tag/Registry.php:116 call_user_func()
textpattern/lib/txplib_publish.php:547 Textpattern\Tag\Registry->process()
textpattern/lib/txplib_publish.php:471 processTags()
```

**Comment by Bloke** [comment]
Hmmm, can you please hack `textpattern/publish.php` and add the debug param to line 150 so it reads `, 1);`

Reload the page and let us know the whole query(ies) it spits out. Might be something odd with the way the query is built.

**Comment by NicolasGraph** [comment]
The same error gives that:

```
Tag error: <txp:article_custom section="a-propos" id="4, 5, 13" wraptag="ul" break="li"><a href='<txp:permlink />'><txp:title /></a></txp:article_custom> ->  Textpattern Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND (from_unixtime(2147483647) <= Expires OR Expires IS NULL) AND ID  IN (4,5,13' at line 1 while parsing form vsv_found_footer on page vsv_found_magazine

textpattern/lib/txplib_db.php:418 trigger_error()
textpattern/lib/txplib_db.php:1162 safe_query()
textpattern/lib/txplib_db.php:1004 startRows()
textpattern/publish.php:850 safe_rows_start()
textpattern/publish.php:971 doArticles()
textpattern/publish.php:960 parseArticles()
article_custom()
textpattern/vendors/Textpattern/Tag/Registry.php:116 call_user_func()
textpattern/lib/txplib_publish.php:547 Textpattern\Tag\Registry->process()
textpattern/lib/txplib_publish.php:471 processTags()

SELECT *, UNIX_TIMESTAMP(Posted) AS uPosted, UNIX_TIMESTAMP(Expires) AS uExpires, UNIX_TIMESTAMP(LastMod) AS uLastMod FROM magtextpattern as textpattern WHERE 1 AND `Posted` <=  AND (from_unixtime(2147483647) <= Expires OR Expires IS NULL) AND ID  IN (5) AND Status >= 4 ORDER BY FIELD(ID, 5), Posted DESC LIMIT 0, 10
```

**Comment by Bloke** [comment]
Aha! `Posted` <=  AND ` is invalid. That might be because you have Posted set to 'none'. It probably does need to be `NOW()`

Please ensure that all your records in the textpattern table have valid timestamps in the Posted column and that the LastMod column is set to 'Posted' so it defaults to a valid timestamp also. Looks the queries assume this is the case.

**Comment by NicolasGraph** [comment]
> That might be because you have Posted set to 'none'. It probably does need to be NOW() doh!

Yes, as mentioned previously, I was able to disable the strict mode and run the upgrade but the default values set are the following:

```
Posted: None
Expires: NULL
LastMod: None
```

…and I'm still not able to set _Posted_ to `NOW()` and LastMod to `Posted`… :-/

**Comment by Bloke** [comment]
Utterly baffling. If there are no Posted or LastMod or Expires values left in your `textpattern` table with values `0000-00-00 00:00:00` and your default values are as you posted above, then there should be no impediment to setting the default values to the ones required: `NOW()`, `NULL`, and `Posted`.

This is very strange indeed. There must be something else at play that I have no idea about. Hope someone else with more MySQL-fu than me has a clue.

**Comment by NicolasGraph** [comment]
> If there are no Posted or LastMod or Expires values left in your textpattern table with values 0000-`00-00 00:00:00` […]

I just checked again and there is no value like `00-00 00:00:00`…

**Comment by NicolasGraph** [comment]
I think _Posted_ is now OK; I previously tried `NOW()` as default value through phpMyAdmin and it didn't work. Using SQL shew me that `NOW()` is in fact equal to `CURRENT_TIMESTAMP`; I was not sure about that.
Now I can't figure how to set _LastMod_ with _Posted_ as default value in SQL. What I tried is not correct…
```
ALTER TABLE magtextpattern MODIFY LastMod DATETIME NOT NULL DEFAULT Posted
```

**Comment by Bloke** [comment]
Ah, pants. It seems I'm mistaken. The bit of the code I was looking at is simply altering the values in the `textpattern` table to match the values in the other columns. Trying to set the default value of one column top the value of another is impossible without triggers. Sorry, my brain's fried today.

Look at `_to_4.6.0.php` around line 212. All it does is modify them and set them all to `NOT NULL` no defaults except for `Expires` which is set to `NULL` by default. Presumably then, we must ensure programmatically that the created / lastmod dates are set properly prior to insertion.

That doesn't however explain how you got the invalid SQL query error earlier. I presumed (wrongly) that was because of the lack of default value in the field. It seems that's not the case and something else is causing that. Might be MLP? So perhaps these two issues are not related at all.

Again, apologies for leading you astray. No idea what's going on today - juggling too much, perhaps and losing the plot a bit.

**Comment by NicolasGraph** [comment]
> Ah, pants. It seems I'm mistaken. […]

Ok, no worry, I was not that fresh too yesterday…
You are right, it comes from MLP, I restored the _/textpattern_ folder and error messages disappeared ; I pasted MLP files again and error messages were back… It's sad for MLP.
