### ISSUE TITLE
Tag builder: the tag builder form is not focussed.

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#751]
STR:

1. launch the tag builder from Pages or Forms panel - focus is set on the “close” button
2. using the keyboard, select (focus) an item to build a tag for , and press Return
3. the actual tag builder form loads in the dialog.
4. try to interact with the form using the keyboard. The focus goes to the first focusable element on the page (the Textpattern logo) not the dialog .

Expected: at step 3 above, the focus is set on either the “close” button (for consistency with step 1 above) or on the “go back” link (which happens to be the first focusable element after the close button).

originally raised in the forums: http://forum.textpattern.com/viewtopic.php?pid=300899#p300899

**Comment by Bloke** [comment]
Hmmmm, on my Windows 7 here (latest Firefox) it behaves. Focus is on the close button each time you submit the form, and tabbing through to the input box seems to happen in a logical order. Which browser / OS are you on?

I'll admit though, it'd be more useful if it focused on the first input element when the form loads. Wonder if that's possible...

We're just investigating auto-selecting the textarea content (ready to copy 'n paste) after hitting the Build button so will look at this focus thing then.

**Comment by bloatware** [comment]
Auto-selecting works ok, but auto-clipboard copy looks unfeasible (needs user interaction). I would
* include `step=build` in links hrefs, to avoid an extra click on "Build" button when the defaults are ok;
* auto-select the output on load and build.

**Comment by Bloke** [comment]
@bloatware Sounds great. Got your JavaScript hat on? If so, by all means go for it!

**Comment by philwareham** [comment]
I wouldn't want auto-clipboard copy anyway, just auto-select is fine.

**Comment by bloatware** [comment]
ok, will test js this evening.

**Comment by phiw13** [comment]
@Bloke 

> Hmmmm, on my Windows 7 here (latest Firefox) it behaves. Focus is on the close button each time you submit the form, and tabbing through to the input box(es) seems to happen in a logical order. Which browser / OS are you on?

Safari on OS X 10.11 fails (the `esc` key also fails at that point fwiw). It does works with Firefox though. I don’t see any errors flagged in the Safari console.

Hmm Safari TP (aka Safari 10) seems to work fine. Puzzling.

> I'll admit though, it'd be more useful if it focused on the first input/select element when the form loads. Wonder if that's possible…

Oh yes, that would be nice.

@philwareham

> I wouldn't want auto-clipboard copy anyway, just auto-select is fine.

+1000

**Comment by philwareham** [comment]
OK, for now we shouldn't let this hold up beta3 (we can slip it into final release). If Stef can run the checksums on master I will release the beta. Cheers everyone.

**Comment by phiw13** [comment]
FWIW I can reproduce the exact same loss-of-focus behaviour with Edge running on Windows 10 build 1511.

**Comment by philwareham** [comment]
So, in essence ideally we should have:

1. Focus on close button when on tag list selector.
2. Focus on first form field (could potentially be either textarea or input so need to be ware of that).
3. Focus on built code textarea when the 'build tag' button is pressed.
4. Select all within the built code textarea when the 'build tag' button is pressed.

Possible with some jQuery?

**Comment by Bloke** [comment]
@philwareham Sounds logical to me. Hopefully @bloatware can wave his magic jQuery wand :-)

**Comment by bloatware** [comment]
Ahem... sorry, missed these comments and done à la bloatware :-) Now, clicks on files/images tags links automatically build and select tags (idem for "Build" button). Please test, I'll revert it if nay, or extend to other tags if yay.

**Comment by bloatware** [comment]
> I wouldn't want auto-clipboard copy anyway, just auto-select is fine.

Copy on build would be opt-in (checkbox), but I don't see how to do it, unless we rewrite the tag builder in js and delegate to the browser. So I will drop the copy-on-build branch if nobody has an idea.

**Comment by philwareham** [comment]
I'm fine with dropping it - the functionality you've already added works well I think.

**Comment by bloatware** [comment]
Done. Auto-select extended to all tag builder links now.

**Comment by Bloke** [comment]
Minor issue with tags that have attributes pre-selected (e.g. Presentation->Pages->Tag builder->Site navigation->Related articles). The label is pre-selected but doesn't show in the textarea on first click, until you click _Build tag_.

Probably nothing to worry about. Very edge case, just thought I'd mention it in case it affects other tags in the builder or there was a simple workaround.

**Comment by phiw13** [comment]
Why is this closed ? The original issue is still not fixed, afaict. 

To recap, when the user interacts with the tag builder from the keyboard, selects / clicks a tag to build, the actual configuration form is then loaded. However the focus is not (anymore) on the `dialog` but on the first focusable element of the *page*. I have reproduced that issue on at least Safari and Edge. It works correctly with Firefox, though.

**Comment by phiw13** [comment]
Regarding the auto-selection of the *Build tag* output. On iOS devices, the textarea is focussed, but the contents is *not* selected. I personally don’t really care about it, but thought it worth mentioning.

**Comment by phiw13** [comment]
Apologies, it is mostly fixed one way: click tag-builder link, the list of possible tags loads, select / click a tag -> config. form loads. This appears to work.

But not the other way.
After doing the above steps ->  edit, etc, close the tag builder - click a second time on the tag-builder link (without saving the page). The tag builder opens with the  config form loaded - tab to the “Go Back” button click (enter key) -> the list of possible tags loads, but the `dialog` is out of focus.

**Comment by bloatware** [comment]
Thank you for testing, I often forget that "works in Firefox" doesn't always mean "fixed". Sorry if some problems persist, let's try to fix them. To recap, there still are two issues:

* `dialog` is not focused after clicking "back" link in some browsers. Confirmed, will investigate.
* the pre-selected attributes are not taken in account until one clicks "Build" button. This is annoying, I wouldn't like to add an extra `click()`. Will need a fix in all tags with default attributes in `txp_tag.php`, I'm afraid.

**Comment by bloatware** [comment]
Please test if [this](https://github.com/textpattern/textpattern/commit/5841a4d89562e00a402ca44035acea67a7403734) fixes the lost focus issue. I had to make "Tag builder" link an open/close switcher, otherwise Firefox loses focus now. :)

**Comment by phiw13** [comment]
@bloatware

Unfortunately, that didn’t fix the issue, at least not with Safari (I haven’t had a chance to play with Edge, yet).

The thing I noticed – the chain: open tag builder --> `dialog` opens with list of tags, select tag --> pane2 of tag builder (config form) opens. There the focus is kept on the dialog **because** the final `textarea` is focussed (and pre-filed). But if you press the “go back” link, the list-of-tags panel loads and the `dialog` loses focus.

**Comment by bloatware** [comment]
@phiw13 That's disappointing. Unfortunately, the closest to Safari that I can test it on is W7 Chrome, and it works. Note that initially the (invisible) focus is on the dialog itself, not on its elements.  Also, please make sure that your browser does not load a staled js file from the cache. I will try to test it in OSX Safari, but not before tomorrow.

**Comment by phiw13** [comment]
@bloatware  yeah, sorry for being the messenger of sad news.

I’ve now had some time to test with MS Edge (W10-build 1511), and the issue remains the same as with Safari. Forward works fine, but pressing the “Go back” link looses the focus.

Everything else in the tag builder works fine in both browsers. So there is that.

**Comment by bloatware** [comment]
Well, [next round](https://github.com/textpattern/textpattern/commit/b782d89aa7a5ba7f751a4366d34d3c7a422efae9). Now works in W10 Edge, at least.

**Comment by phiw13** [comment]
> Well, next round. Now works in W10 Edge, at least.

Yes sir!  Ship it!

**Comment by philwareham** [comment]
Great work everyone! Checked in Safari 9 and works well. Closing.
