### ISSUE TITLE
Consider Moving two Article preferences to either above or below Body and Excerpt fields

### ISSUE THREAD

**Issue by bici** [textpattern/textpattern#887]
See this discussion https://forum.textpattern.io/viewtopic.php?pid=304837#p304837
I would consider a toggle to On or Off On to see te options and then off. Could be set by user to always on by default to off

**Comment by philwareham** [comment]
Like [this?](http://design-patterns.textpattern.io/mockups/content-article.html)

**Comment by bici** [comment]
i think that looks marvellous! and not overly intrusive. thanks

**Comment by philwareham** [comment]
@Bloke over to you then!? ;)

**Comment by tecumsehmaverick** [comment]
Just another perspective, fwiw.

I have been aware of those options were, so I do not have the same felt need for them to have great visibility.  I personally think it is more elegant, and a cleaner UI to have options on the side, and just content fields in the middle (as much as possible).

That said, it's not a huge deal if they are moved.  bici's mock up isn't bad looking either. Just not my first choice.

What for me would be a bigger issue is the upcoming unlimited custom fields.   Each field will have the potential for a markup language as I understand it?  So if I add several more fields, if we are consistent we now have extra options with each field?  That would be clunky imo.

As I said, just another perspective.

**Comment by philwareham** [comment]
@tecumsehmaverick those of of course valid points also. Regarding custom fields there would need to be some tie-up between custom fields (textareas) and their markup preference though, so they'd need to be paired together like the above example. I agree it's extra cruft that cannot be hidden inside a side panel though, and I like less UI not more.

The mockup is just for discussion hence why I've differed to @Bloke.

**Comment by bici** [comment]
Thanks tecumsehmaverick - having used EE for years with unlimited custom fields each with formatting choice,  it is not a burden at all in terms of screen usage. In the other CMS one can toggle other custom fields to be open/visible by default or to only open when needed;  easily manageable. But i agree with you a UI is very personal. Too minimal in my view with an important Textual option, way off off to the side with no visible clue as to what it  belongs/affects is not something that i ever used...it was unclear to me what that option was meant for!   Now that i have used it is perfectly clear. but overall in my opinion it belongs CLOSE to the TEXT fields where a user is writing.

**Comment by Bloke** [comment]
@tecumsehmaverick That's a good point. The plan is indeed to have markup per field -- at least for the text-based ones, and it will get... cluttered if we follow the same layout model there.

That's kind of why I advocated the use of a text link (like we have for the Tag builder on the Forms/Pages panels) which pops up a dialog to change the scheme for that field. The markup scheme for the associated textarea is still visible right above it, but it doesn't take up as much space until you actually need it.

**Comment by tecumsehmaverick** [comment]
I appreciate that Phil. As I said, just wanted to add another perspective as the discussion progresses. I too am for simple, just not sure that looks clean and simple to me.

Bici - It's been years since I used EE. My more recent experience with a CMS offering unlimited custom fields has been Symphony.  It's approach is quite different. You usually set the mark up choice on the edit page where you create your custom fields. The choice is not generally present when entering content.  It makes it more complicated to change, but a simple interface for the end user.

For me, I've so rarely used those options - maybe a couple of times in ten or eleven years, that I process it as page noise. 

The pop up option like a nice way to have it quickly accessible but minimize the intrusion. Text link, or even a little i icon (or similar) that lets you set the various options for that field.

But as I said, I'm good how ever it turns out.

**Comment by philwareham** [comment]
I did have a mockup somewhere in the past that had moved the Text filter help (as a dialog box link) to the top left of the textarea - it wouldn't be too much of a stretch to also have something like that for selecting which text filter you want to use. Leave it with me and I'll throw something together in next few days.

**Comment by bici** [comment]
tecumsehmaverick - total  agreement.  I have only used the Text Option once! - this week. But when i used EE it was second nature to have those options to toggle. The default setting required no adjustments and those settings were easy to ignore. But i think with many custom fields there is power in having that option underneath the field. I used it a lot!  BUT i can live and adjust to whatever avenue the devs. wish to go. Now that i have twigged onto the option and it's location.  DEVS: Keep up the good work.

**Comment by philwareham** [comment]
Maybe [roughly like this?](http://design-patterns.textpattern.io/mockups/content-article2.html). Dunno, still seems a bit clunky, but I guess you do need to visually see which text filter is in currently in effect.

**Comment by tecumsehmaverick** [comment]
Yes, echoing bici - thank you Phil and Stef, and keep up the good work.

**Comment by Bloke** [comment]
@philwareham Yeah. Body one looks great. Excerpt looks not as great as in my head. Kinda messes up a bit when the 'instructions' are used. I'd forgotten about those.

If you have a mockup with the textfilter help too, then by all means factor it in and we'll see if it works. It does feel kinda right to have the markup option near the field in which it's used. Just gotta figure out the specifics.

**Comment by phiw13** [comment]
> Maybe roughly like this?

That would get me vote. Maybe, just thinking out loud, make only the “Text filter” string an active link, with the active markup language just plain (black or greyish?) text.

The “help” text tied with the `excerpt` field is a bit disturbing though. If that ever comes to a real panel, would the user have the option to hide it (permanently) – as in, use the little “i” link to show/hide it?

**Comment by philwareham** [comment]
The description text is a 'hidden feature' that is in Textpattern 4.6 onwards. It allows power users to add their own descriptions to any field in the CMS. I guess it should be documented somewhere sometime. @Bloke

**Comment by tecumsehmaverick** [comment]
a couple follow up thoughts 

imo, Bici's suggestion of moving it to the bottom is worth considering.  Alt, as Jakob mentioned in the forum, a gear icon would also work. Maybe right next to the "i" icon . . . 

But I can see you have it well in hand. I'll drop off the discussion unless some grand light of brilliance should seize upon me. :)

**Comment by Bloke** [comment]
Yeah the instructions fields needs adding to the docs somewhere. Just no idea where it belongs. It's not exactly a callback, more a theme / language / internationalisation feature. Ponder...

**Comment by gocom** [comment]
That looks nice; of course as long as the options hides itself if there is only one formatting option available. (If it is possible to remove them; didn't it internally use callback_ref(), in which case it is?).

**Comment by philwareham** [comment]
@gocom hey man, good to see you back.

I'll continue experimenting with this UI change during the week. Think it has potential, especially with dual Markdown/Textile options hopefully in core someday (or in an official plugin).

**Comment by bloatware** [comment]
> It does feel kinda right to have the markup option near the field in which it's used.

+1. Near the field label, maybe?

**Comment by bici** [comment]
@philwareham re "Markdown/Textile options hopefully in core someday (or in an official plugin)"
I vote for it in Core someday.

**Comment by philwareham** [comment]
OK, I've [updated the second visual](http://design-patterns.textpattern.io/mockups/content-article2.html) based on latest discussions (might need to refresh browser).

So:

1. The 'text filter' text is the clickable item, which in theory would open a dialog box where you can choose from any installed text filters (I guess we could also have some link here which takes you to an external page listing all available text filters).
2. The 'i' link next to the active text filter would open a pophelp with the text filter help in it (instead of currently have that panel in the sidebar wasting more space). Since we are going to bundle pophelp files with the system from 4.7 onwards I think this is achievable.

Thoughts?

**Comment by philwareham** [comment]
Also, yes we've put the 'override form' control into the sort/display panel which is more clutter (as the sort/display is uncollapsible) but remember that you can disable override globally in the prefs which takes this field out of the flow anyway.

**Comment by bloatware** [comment]
Visually fine with me. Unrelated, but we should put categories in a separate collapsible panel one day.

**Comment by phiw13** [comment]
Looks OK, discreet but still easily discoverable.

And yes, the sort / display panel is a bit more cluttered now. Would @bloatware‘s suggestion (split up the panel) be lots of (complicated) work?

**Comment by Bloke** [comment]
Looks great for the default layout and is also extensible for unlimited custom fields when they come online. I love that the Textfilter help can be moved inline with the control too: one less twisty in the side panel, yay!

Override form is fine where you put it. As you say, if you don't use it, turn it off.

Splitting up categories and sections, sure. The Section is the only mandatory sidebar item for an article, so it makes sense to bundle that up with the (optional) Form override (and call the uncollapsible panel, errr, what?), then put categories into their own twistable panel. It's due for a rethink when we find a way to do unlimited cats/tagging anyway, so it's a good first step towards that goal.

**Comment by philwareham** [comment]
Somewhat related to this:

* [declutter] It would be nice if there was a pref option to remove the 'Recent articles' panel on the write page. I never use it and it'd be nice to have a core way to disable it.
* The pref wording 'Use Textile' is wrong, really. It should be something like 'Default text filter' and then the options (which are then mirrored in the write page text filter options per textarea too):
  * Textile
  * Markdown (e.g. if the current wet_textfilter_markdown is installed)
  * Raw
  * Raw with line breaks
* There are a few other places that Textile is directly mentioned (such as 'Allow more Textile markup in comments?' - this should be made more flexible in future to allow for other text filters or be removed from flow when not using Textile).

**Comment by philwareham** [comment]
Re: categories in a separate panel, [here is a new visual](http://design-patterns.textpattern.io/mockups/content-article3.html) with that multiple categories theory in place and minimal other panels/fields available (i.e. no custom fields being used, recent articles display turned off, comments system off, override form off).

**Comment by Bloke** [comment]
Core option to remove the recent articles block? Sure, why not. Can't think of a non-preffy way of doing it. If you allow the panels to be 'dismissed' directly (an 'x' button) then how do you get them back? We'd have to introduce some kind of 'View' thing to turn them on and off like they do in regular desktop UIs. Is that desirable? Better than a pref?

And yes, I like the minimal look of the latest visual. Very cool. It's not hard work to do - a few callbacks might need tweaking in the 'sort and display' area -- but it shouldn't be too bad. Want me to tackle it? Or does anyone else call dibs?

**Comment by tecumsehmaverick** [comment]
Perhaps "Raw" would be better as one of the following?

Text
Plain Text
Unformatted

Raw seems to be more of a Git coding term than a writing term.

Tangent on text formatters.

I understand that Textile v. Markdown debate.  I personally find Textile more elegant than Markdown and more sensible in its shorthand. However I recognize the prevalence of Markdown these days.

I'm the very odd man out on this.  While I use Textile when writing in Textpattern, in the back of my mind I am always wondering why we add layer upon layer upon layer.  html was meant to mark up the language. Then we decide that's too hard to learn, so we create another mark up language that stands between us and html.  Then we create GUI to stand between the lighter markup language and us because that is too hard.

If we are going to use a mark up language, I'm okay with it being the original, base language of html. But that's me and as I said, I am really the odd man out on this.

When we use a graphical user interface (which I like to use sometimes, like most people) - whether a WYM or a WYSIWYG, or something like rah_textile_bar, why not skip the intermediate mark up languages and go straight to a GUI for html. Again, I personally think less is more.

All that to say:  I'd rather you make all text formatters optional, including Textile, than include both Textile and Markdown by default in the core.

**Comment by tecumsehmaverick** [comment]
re: the override form

I have used it maybe once. Maybe. So mostly I don't care if it is available. But out of curiosity, if I have used it, say once or twice, does that mean I have to always leave it on from that point forward?  Or can I turn it on, use it. Then change the preference to hide it again, so that I don't to work over it the rest of the time?

(I am presuming the former scenario?)

**Comment by Bloke** [comment]
@tecumsehmaverick If you turn the override form feature off at a later date, any forms you have set to override individual article flow will be ignored when displaying the articles on the public site,

**Comment by philwareham** [comment]
@bloke please call dibs on this and work it up into actual code.

Regarding the recent articles panel just leave that in place for the moment without the pref - as thinking about it a bit more, how we show/remove panels from the write page should be tied into to the definable custom fields work. I don't want to introduce a pref that is redundant one Textpattern version later.

**Comment by philwareham** [comment]
@tecumsehmaverick OK, I've amended visuals 2 and 3 with 'Plain text' instead of 'Raw'. Makes sense.

**Comment by tecumsehmaverick** [comment]
@philwareham 

re: the override form:  Thanks Phil. That is what I presumed to be the case.  And if it is turned on again, was the original override setting lost/deleted?  Or does it return? (Perhaps that is in the documentation. I'll take a look.)

re: Raw v. Plain Text.  Sorry if it sounded nit-picky, and thanks! 👍

**Comment by bici** [comment]
It looks good. i have a slight preference for the text chooser to be underneath the text box, but i am also  fine with it as it is,  i like that is very unobtrusive. 
 I also prefer "Plain Text" ( or "None")  to "Raw" but again happy as is.

great work ... thanks to all involved

**Comment by Bloke** [comment]
> if [override form] is turned on again, is the original override setting lost/deleted? Or does it return?

That depends:

* When you turn it off, your public site will use the default page/form flow.
* If you turn it back on again, any articles that had previously been assigned an override form will get that same override form back, and their publishing flow will be diverted accordingly on the public site.
* BUT, if you've since edited and saved any article that had an override form set up, the setting will be lost. This is because that column's content is not loaded into the Write panel when the pref setting is off, so when you save, the field is "empty" and is thus saved in that state, overwriting what (if anything) was there.

**Comment by tecumsehmaverick** [comment]
Thanks for the explanation Bloke!

**Comment by philwareham** [comment]
Updated the mockup to have a dropdown menu - let me know if that UI idea works for you: http://design-patterns.textpattern.io/mockups/content-article2.html

**Comment by phiw13** [comment]
That drop down works fine for me. It is probably the most unobtrusive solution. (I was going to comment that Textile / Markdown should come first in the list, but then realised that TXP 4.6 has the same order; tells you how any times I used that selector).

Small nitpick though, the “+” in the “Plain Text + line breaks” line really should be a “with” – it *might* work fine in English (dunno), but for various other languages it would look quite weird.

But the Write screen becomes quite “dense”, particularly on small(er) screens.
You moved the author line to under the Title field a couple of commits ago. I am not sure it is a good idea, as it adds lots of density to the screen to the point of being annoying. I’d prefer to see it move back to the end of the column, under the Excerpt field.

**Comment by bici** [comment]
nirvana !   
(using safari)

**Comment by Bloke** [comment]
[This commit](https://github.com/textpattern/textpattern/commit/a8185537127cc475b9e88b75dbbeb3f01b729132) finishes off the inline dropdown menus. Well, apart from the help links, which are yet to be resolved. Ideas welcome.

Caveat: it *will not work* without a new language string that you'll need to add to your DB manually until it's rolled into the lang pack:

```
#@article
textfilter => Textfilter: {filter}
```

Please test and report back.

**Comment by Bloke** [comment]
Oh, we do have one other possible cause for concern: what happens if there's only one textfilter in use? At the moment it's rendered anyway. Logic dictates that the entire menu and 'Textfilter: <name of filter>' should be omitted, as there's no choice to be made. But that would also mean the help link would be omitted.

Might a user who is operating under a single filter still wish to obtain help on the (sole) filter their administrator has made available to them? If so, where should the 'i' link go when it has no associated furniture to attach it to?

Of course, this is moot if we can't figure out how to actually serve suitable (i18n) help text for the currently selected filter anyway.

**Comment by tecumsehmaverick** [comment]
Thinking aloud:

* Less is [usually] more 

* What real help is there to offer if there are no choices?  

* When setting up an install if I want to standardize on a single text formatter, why even hint that there could be more by having the help link?  Why inspire questions or perplexity?

**Comment by philwareham** [comment]
Question is, do we provide any hints as to how the text filter formats text? If you are happy to offer no explanation then I guess help can be removed here. How do other CMSes handle this?

Won't 'Keave text untouched' and 'line breaks only' always be available or can you turn those off?

**Comment by Bloke** [comment]
@tecumsehmaverick Currently we have a side panel called 'Textile Help' which houses a few odds and ends of markup assistance (bold, italic, links, etc) and a link to txstyle.org for more info. That entire twisty block is going to be removed, with the intention of putting that help stuff next to the filter, if you've chosen Textile as your filter. So anyone who either a) picks Textile, or b) has Textile as their only markup option, has some help topics available to help them get to grips with the markup.

If a plugin offers Markdown, similarly, some help text ought to be present -- even if it's just a link to daringfireball.com.

The issues we have:

1) Textfilter help is provided in the Filter etc (in code) and is thus not language-sensitive.
2) The help 'i' link destination needs to change on-the-fly to offer a topic based on the chosen textfilter.
3) Help topics are currently served by RPC or, from 4.7.0 onwards, from static files in the `lang` directory. Keeping those up-to-date with (e.g.) Textile tag information is fine for built-in filters, but not very helpful for third party filters that plugins might provide.

So we need to figure all this out: do we drop the help topics entirely and present only a URL off the 'i' for each filter? In which case we need to refactor the Textfilter system, as it currently has an ill-implemented help feature built in.

**Comment by Bloke** [comment]
> Won't 'Leave text untouched' and 'line breaks only' always be available or can you turn those off?

A plugin can override them and, thus, remove them, perhaps offering Hobson's choice to writers.

**Comment by philwareham** [comment]
To help make testing easier, I've now added strings to RPC - update languages and you'll see it. Not added translations until we know what correct text will be.

**Comment by tecumsehmaverick** [comment]
I was having a brain freeze. I was thinking help in terms of explaining what a text formatter was, or how help switching between Markdown and Textile, etc.  

Phil's point about leave untouched and line breaks only, as well as the point about quick formatting help makes it clear that help is appropriate there. I had forgot about the Textile quick help cheat sheet - It has been a while since I used it, but I have used it in the past.

Sorry for the noise.

But the way - not sure how hard it would be to pull out the help from the filter itself, but if general txp plugins are moving towards separate files for help vs code (ala Jukka and Jeff practices), it seems like a nice standard for the formatters to follow as well.  Perhaps some sort of code wizardry that notes the option selected and then only loads the relevant [linked] help file?

Bonus - the default textile help could be small, but easily customized to be more extensive if desired.

**Comment by philwareham** [comment]
I've fixed up the HTML for this dropdown now. Just needs the help link fixed - but that should probably wait for the work on moving the help files into the CMS, since we haven't decided on the best thd for that yet.

**Comment by phiw13** [comment]
Still doesn’t work well for a keyboard user: how does one actually selects an item from the keyboard (any browser)?

On the list panels, the menu under “List options” (or Search) ‘works’ as one can actually tab through the checkboxes. Here there is nothing. Also wonder (I haven’t had the opportunity to test) if it works on touch devices, and with screen readers.

Wouldn’t the menu on the write panel need a `<a href=#>` to be fully functional?

Hmm, now that I test this again, using Safari / Opera / Edge, the dropdown menus on the list panels are not really functional either, for a keyboard user. One can tab to the checkboxes, but pressing spacebar does not toggle their state (there is a visual feed back Edge - default “active” state of the checkbox, but no actually action).

e. g. Search: tab from the textfield. Press return on the last button, the dropdown opens; press tab, the first item is highlighted (visually focussed at least - arrow down moves that focus), press tab again, the checkbox is focussed. But pressing the spacebar does nothing. I can’t find a way to trigger a toggle the state otherwise (from the keyboard that is…).

Perhaps it is my imagination that it actually worked at one point.

On the list panels, it kinda work with Firefox, though.

**Comment by philwareham** [comment]
@bloke I think before we go any further we need to agree on how we are going to implement pophelp within the system. See https://github.com/textpattern/textpattern/issues/838 and (older) https://github.com/textpattern/textpattern/issues/292.

I think we can close this particular issue and continue conversation in one or other of those issues?

**Comment by Bloke** [comment]
Yes, this issue now crosses into pophelp, which is tied to the `languages-inclusion` branch so I was going to merge dev there and continue.

The only reason I left this open is because of phiw13's negative experience with the keyboard navigation aspect. Is that fixable/fixed?

**Comment by philwareham** [comment]
Ok, please open issue and I'll investigate
